"""add mood_entries and song_preferences tables

Revision ID: 89f15ba6a167
Revises: 
Create Date: 2026-04-13 08:34:54.190540
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f15ba6a167'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('base_emotion', sa.String(length=50), nullable=False),
    sa.Column('sub_emotion', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('input_preview', sa.String(length=100), nullable=False),
    sa.Column('weather_condition', sa.String(length=50), nullable=False),
    sa.Column('mood_emoji', sa.String(length=10), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_entries_created_at'), 'mood_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_mood_entries_user_id'), 'mood_entries', ['user_id'], unique=False)
    op.create_table('song_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('song_key', sa.String(length=255), nullable=False),
    sa.Column('preference', sa.String(length=10), nullable=False),
    sa.Column('song_title', sa.String(length=255), nullable=False),
    sa.Column('song_artist', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'song_key', name='uq_user_song')
    )
    op.create_index(op.f('ix_song_preferences_song_key'), 'song_preferences', ['song_key'], unique=False)
    op.create_index(op.f('ix_song_preferences_user_id'), 'song_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_preferences_user_id'), table_name='song_preferences')
    op.drop_index(op.f('ix_song_preferences_song_key'), table_name='song_preferences')
    op.drop_table('song_preferences')
    op.drop_index(op.f('ix_mood_entries_user_id'), table_name='mood_entries')
    op.drop_index(op.f('ix_mood_entries_created_at'), table_name='mood_entries')
    op.drop_table('mood_entries')
    # ### end Alembic commands ###
